apiVersion: apps/v1
kind: Deployment
metadata:
  name: attrition-backend
  namespace: employee-attrition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attrition-backend
  template:
    metadata:
      labels:
        app: attrition-backend
    spec:
      containers:
      - name: attrition-backend
        image: siddhesh01/employee_attrition1-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: model-storage
          mountPath: /app/pickle/models
        - name: app-logs
          mountPath: /app/log
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-data-pvc
      - name: app-logs
        persistentVolumeClaim:
          claimName: app-logs-pvc