apiVersion: apps/v1
kind: Deployment
metadata:
  name: attrition-frontend
  namespace: employee-attrition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attrition-frontend
  template:
    metadata:
      labels:
        app: attrition-frontend
    spec:
      containers:
      - name: attrition-frontend
        image: siddhesh01/employee_attrition1-frontend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REACT_APP_API_URL
          value: "http://backend-service:8001"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config